/**
 * 项目通用存储Key
 */
export class StorageKeys {
  static readonly APP_KEY = "app_key";
  static readonly USER_INFO_KEY = "user_info_key";
  static readonly USER_LOGIN = "user_login";
  static readonly TOKEN = "token";
  static readonly APP_VERSION_NAME = "version_name";
  static readonly USER_INFO = "user_info";
  static readonly USER_ID = "user_id";
  static readonly USER_NAME = "user_name";
  static readonly HOME_ID = "home_id";
}